import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowRight, BarChart3, Bell, Bot, Check, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, FileCheck2, FileText, GraduationCap, Home, LayoutDashboard, Menu, MessageCircle, Moon, Plus, RefreshCw, Search, Send, Settings, ShieldAlert, Sparkles, Sun, Upload, UserPlus, Users, WalletCards, X, Zap} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL+'/api';
async function api(path, opts={}){
  const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});
  if(!r.ok){const e=await r.json().catch(()=>({detail:'Request failed'}));throw new Error(e.detail||'Request failed')}
  return r.json();
}
const label=s=>({NEW_LEAD:'New lead',QUALIFIED:'Qualified',DOCUMENTS_PENDING:'Documents',PAYMENT_PENDING:'Payment',ELIGIBILITY_REVIEW:'Eligibility',ENROLLED:'Enrolled',ESCALATED:'Escalated'}[s]||s);

function App(){
  const [page,setPage]=useState('home'),[students,setStudents]=useState([]),[selected,setSelected]=useState(''),[analytics,setAnalytics]=useState({}),[ai,setAi]=useState(null),[toast,setToast]=useState(''),[dark,setDark]=useState(true),[mobile,setMobile]=useState(false),[refreshing,setRefreshing]=useState(false);
  const [notice,setNotice]=useState(false);
  const refresh=async()=>{setRefreshing(true);try{const [s,a,g]=await Promise.all([api('/students'),api('/analytics'),api('/ai/status')]);setStudents(s);setAnalytics(a);setAi(g);if(!selected&&s[0])setSelected(s[0].id)}catch(e){setToast('Backend is offline. Start FastAPI on port 8000.')}finally{setRefreshing(false)}};
  useEffect(()=>{refresh()},[]); useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t)},[toast]);
  const go=p=>{setPage(p);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})};
  const nav=[['home','Command Center',LayoutDashboard],['copilot','AI Copilot',Bot],['leads','Leads & Students',Users],['journey','Student Journey',Activity],['documents','Documents',FileCheck2],['analytics','Analytics',BarChart3],['settings','Settings',Settings]];
  return <div className={dark?'app dark':'app'}>
    <aside className={mobile?'sidebar open':'sidebar'}>
      <div className="brand"><div className="brandMark"><Sparkles size={18}/></div><div><b>GIET<span>AI</span></b><small>Admissions OS</small></div><button className="mobileClose" onClick={()=>setMobile(false)}><X size={18}/></button></div>
      <div className="live"><i/> Agent online <span>{ai?.configured?'Gemini connected':'Demo mode'}</span></div>
      <nav>{nav.map(([id,t,I])=><button className={page===id?'active':''} key={id} onClick={()=>go(id)}><I size={18}/><span>{t}</span>{id==='copilot'&&<em>AI</em>}</button>)}</nav>
      <div className="sideBottom"><button onClick={()=>setNotice(v=>!v)}><Bell size={17}/> Notifications <b>{analytics.open_escalations||0}</b></button><button onClick={()=>go('settings')}><Settings size={17}/> Control center</button></div>
    </aside>
    <main>
      <header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><span className="crumb">GIET UNIVERSITY · AUTONOMOUS ADMISSIONS</span><h1>{nav.find(n=>n[0]===page)?.[1]||'Command Center'}</h1></div><div className="headerTools"><button className="refresh" onClick={refreshing?undefined:refresh}>{refreshing?<span className="spin"><RefreshCw size={16}/></span>:<RefreshCw size={16}/>} <span>Sync</span></button><button className="icon" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><div className="avatar">AC</div></div></header>
      {notice&&<div className="notice"><ShieldAlert size={17}/><div><b>{analytics.open_escalations||0} open escalations</b><span>Human review items are waiting in the workflow.</span></div><button onClick={()=>{setNotice(false);go('journey')}}>Open <ArrowRight size={14}/></button></div>}
      <section className="content">
        {page==='home'&&<HomePage a={analytics} students={students} go={go} select={id=>{setSelected(id);go('journey')}} toast={setToast}/>} 
        {page==='copilot'&&<Copilot students={students} selected={selected} setSelected={setSelected} reload={refresh} toast={setToast}/>} 
        {page==='leads'&&<Leads students={students} select={id=>{setSelected(id);go('journey')}} reload={refresh} toast={setToast}/>} 
        {page==='journey'&&<Journey students={students} selected={selected} setSelected={setSelected} reload={refresh} toast={setToast}/>} 
        {page==='documents'&&<Documents students={students} selected={selected} setSelected={setSelected} reload={refresh} toast={setToast}/>} 
        {page==='analytics'&&<Analytics a={analytics} students={students}/>} 
        {page==='settings'&&<SettingsPage dark={dark} setDark={setDark} ai={ai} toast={setToast}/>} 
      </section>
    </main>
    {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
  </div>
}

function Top({eyebrow,title,text,action,onClick}){return <div className="top"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{action&&<button className="primary" onClick={onClick}>{action}<ArrowRight size={16}/></button>}</div>}
function Stat({icon:I,label,value,sub}){return <div className="stat"><div className="statIcon"><I size={18}/></div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function HomePage({a,students,go,select,toast}){const stages=Object.entries(students.reduce((x,s)=>(x[s.stage]=(x[s.stage]||0)+1,x),{}));return <div className="page enter"><section className="hero2"><div className="heroText"><div className="eyebrow"><span className="pulse"/> AUTONOMOUS LOOP · LIVE</div><h2>Turn admission interest into <i>enrollment.</i></h2><p>A clean command center for lead qualification, conversations, documents, payment, eligibility and human escalation.</p><div className="actions"><button className="primary" onClick={()=>go('copilot')}>Open AI Copilot <Bot size={17}/></button><button className="secondary" onClick={()=>go('leads')}>View all leads <Users size={17}/></button></div><div className="heroMeta"><span><Check/> Context preserved</span><span><Check/> Friction detection</span><span><Check/> Human handoff</span></div></div><div className="heroVisual"><div className="core"><Bot size={30}/><b>GIET AI</b><small>{a?.conversion||0}% conversion</small></div><div className="ring r1"/><div className="ring r2"/><div className="node n1">QUALIFY</div><div className="node n2">DOCUMENT</div><div className="node n3">ESCALATE</div><div className="node n4">ENROLL</div></div></section><div className="stats"><Stat icon={Users} label="Leads" value={a?.total??0} sub="All channels"/><Stat icon={Zap} label="Qualified" value={a?.qualified??0} sub="AI-qualified"/><Stat icon={GraduationCap} label="Enrolled" value={a?.enrolled??0} sub="Converted"/><Stat icon={ShieldAlert} label="Escalations" value={a?.open_escalations??0} sub="Need humans"/></div><div className="two"><section className="panel"><div className="panelHead"><div><span className="eyebrow">PRIORITY QUEUE</span><h3>Students needing attention</h3></div><button className="textBtn" onClick={()=>go('leads')}>Open CRM <ChevronRight size={15}/></button></div>{students.slice(0,4).map(s=><StudentMini key={s.id} s={s} onClick={()=>select(s.id)}/>)}</section><section className="panel"><div className="panelHead"><div><span className="eyebrow">LIFECYCLE</span><h3>Where leads are now</h3></div></div><div className="stageList">{stages.map(([k,v])=><div className="stage" key={k}><div><span>{label(k)}</span><b>{v}</b></div><div className="stageBar"><i style={{width:`${Math.max(8,v/Math.max(1,students.length)*100)}%`}}/></div></div>)}</div><button className="wideBtn" onClick={()=>go('analytics')}>Open conversion analytics <BarChart3 size={16}/></button></section></div></div>}
function StudentMini({s,onClick}){return <button className="studentMini" onClick={onClick}><div className="avatar">{initials(s.name)}</div><div className="personText"><b>{s.name}</b><span>{s.program}</span></div><div className="miniStage">{label(s.stage)}</div><ChevronRight size={16}/></button>}
function initials(n){return n.split(' ').map(x=>x[0]).join('').slice(0,2)}

function Copilot({students,selected,setSelected,reload,toast}){const s=students.find(x=>x.id===selected)||students[0];const [messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[source,setSource]=useState(''),bottom=useRef(null);useEffect(()=>{if(!s)return;api('/students/'+s.id).then(d=>setMessages(d.conversation||[])).catch(()=>{})},[s?.id]);useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages]);const send=async(q=text)=>{if(!q.trim()||!s||busy)return;setText('');setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);try{const d=await api('/chat',{method:'POST',body:JSON.stringify({student_id:s.id,message:q})});setMessages(m=>[...m,{role:'assistant',text:d.reply}]);setSource(d.source||'gemini');await reload();}catch(e){toast(e.message)}finally{setBusy(false)}};return <div className="page enter"><Top eyebrow="CONVERSATIONAL AGENT" title="AI Copilot, without the clutter." text="One focused workspace. Ask a question, watch the workflow react, and keep the student context beside the conversation."/><div className="copilotLayout"><section className="chat panel"><div className="chatTop"><div className="agent"><div className="botIcon"><Bot size={19}/></div><div><b>GIET Admissions Agent</b><span>{busy?'Thinking…': source==='gemini'?'Gemini AI · Ready':'Ready'} · {s?.name||'No student'}</span></div></div><select value={s?.id||''} onChange={e=>setSelected(e.target.value)}>{students.map(x=><option value={x.id} key={x.id}>{x.name} · {x.id}</option>)}</select></div><div className="messages">{messages.map((m,i)=><div className={'message '+m.role} key={i}><div className="bubble">{m.text}</div></div>)}{busy&&<div className="message assistant"><div className="bubble typing"><i/><i/><i/></div></div>}<div ref={bottom}/></div><div className="quick">{['What programs suit me?','What documents are missing?','Tell me about fees','How does hostel work?'].map(q=><button key={q} onClick={()=>send(q)}>{q}</button>)}</div><div className="composer"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask the admissions agent…"/><button className="send" disabled={busy} onClick={()=>send()}><Send size={18}/></button></div></section><aside className="sidePanel"><Profile s={s}/><Next s={s}/></aside></div></div>}
function Profile({s}){if(!s)return <div className="panel empty">Create a lead first.</div>;return <section className="panel profile"><div className="profileHead"><div className="avatar big">{initials(s.name)}</div><div><h3>{s.name}</h3><span>{s.id}</span></div></div><div className="score"><div className="scoreNum">{s.conversion}%</div><div><b>Conversion signal</b><span>{s.score}/100 intent score</span></div></div><div className="profileRows"><div><small>Program</small><b>{s.program}</b></div><div><small>Stage</small><b>{label(s.stage)}</b></div><div><small>Channel</small><b>{s.source}</b></div></div>{s.frictions?.length>0&&<div className="friction"><small>Friction detected</small>{s.frictions.map(f=><span key={f}>{f}</span>)}</div>}</section>}
function Next({s}){if(!s)return null;const t=s.stage==='DOCUMENTS_PENDING'?'Complete documents':s.stage==='PAYMENT_PENDING'?'Collect payment':s.stage==='ESCALATED'?'Counselor review':s.stage==='ENROLLED'?'Start onboarding':'Continue qualification';return <section className="panel next"><span className="eyebrow">NEXT BEST ACTION</span><div className="nextIcon"><Zap size={19}/></div><h3>{t}</h3><p>The agent recommends this as the next step in the current lifecycle.</p><div className="nextLine"><CheckCircle2 size={16}/> Context will be preserved</div></section>}

function Leads({students,select,reload,toast}){const [q,setQ]=useState(''),[show,setShow]=useState(false);const filtered=students.filter(s=>(s.name+' '+s.id+' '+s.program).toLowerCase().includes(q.toLowerCase()));return <div className="page enter"><Top eyebrow="CRM" title="Leads & students" text="Simple enough to scan in seconds, detailed enough to demo the autonomous workflow." action="Add lead" onClick={()=>setShow(true)}/><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search student, ID or program"/></div><span>{filtered.length} profiles</span></div><section className="panel tablePanel"><div className="tableHead"><span>Student</span><span>Program</span><span>Stage</span><span>Intent</span><span/></div>{filtered.map(s=><button className="tableRow" key={s.id} onClick={()=>select(s.id)}><div className="personCell"><div className="avatar">{initials(s.name)}</div><div><b>{s.name}</b><span>{s.id} · {s.source}</span></div></div><span className="programCell">{s.program}</span><span className="badge">{label(s.stage)}</span><b>{s.score}/100</b><ChevronRight size={16}/></button>)}{!filtered.length&&<div className="empty">No student matched that search.</div>}</section>{show&&<LeadModal close={()=>setShow(false)} reload={reload} toast={toast}/>}</div>}
function LeadModal({close,reload,toast}){const [f,setF]=useState({name:'',email:'',phone:'',program:'',source:'Website',preferred:'WhatsApp'}),[busy,setBusy]=useState(false);const submit=async()=>{if(!f.name.trim())return;setBusy(true);try{await api('/leads',{method:'POST',body:JSON.stringify(f)});await reload();toast('Lead created successfully');close()}catch(e){toast(e.message)}finally{setBusy(false)}};return <div className="modalBg"><div className="modal"><button className="close" onClick={close}><X/></button><span className="eyebrow">AI INTAKE</span><h3>Create a student profile</h3><p>The agent starts with a clean lifecycle record.</p>{Object.entries(f).map(([k,v])=><label key={k}>{k}<input value={v} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<button className="primary full" disabled={busy||!f.name} onClick={submit}>{busy?'Creating…':'Create profile'} <ArrowRight size={16}/></button></div></div>}

function Journey({students,selected,setSelected,reload,toast}){const s=students.find(x=>x.id===selected)||students[0];const stages=['NEW_LEAD','QUALIFIED','DOCUMENTS_PENDING','PAYMENT_PENDING','ELIGIBILITY_REVIEW','ENROLLED'];const idx=stages.indexOf(s?.stage);return <div className="page enter"><Top eyebrow="LIFECYCLE" title="Student journey" text="See exactly where one student is, what is blocking them, and what the system can do next."/><div className="selectorBar"><select value={s?.id||''} onChange={e=>setSelected(e.target.value)}>{students.map(x=><option key={x.id} value={x.id}>{x.name} · {x.id}</option>)}</select><button className="secondary" onClick={()=>toast('Journey snapshot refreshed')}>Refresh snapshot <RefreshCw size={15}/></button></div>{s&&<><section className="panel journeyCard"><div className="journeyIdentity"><div className="avatar big">{initials(s.name)}</div><div><span className="eyebrow">CURRENT PROFILE</span><h3>{s.name}</h3><p>{s.program}</p></div><div className="journeyScore"><b>{s.conversion}%</b><span>conversion signal</span></div></div><div className="timeline">{stages.map((st,i)=><div className={'step '+(i<=idx?'done':'')+(st===s.stage?' current':'')} key={st}><div className="stepDot">{i<idx?<Check size={14}/>:i===idx?<Activity size={14}/>:i+1}</div><b>{label(st)}</b><span>{i<=idx?'Completed':'Upcoming'}</span></div>)}</div></section><div className="two"><section className="panel"><div className="panelHead"><div><span className="eyebrow">BLOCKERS</span><h3>What is stopping progress?</h3></div></div>{(s.frictions?.length?s.frictions:['No friction detected']).map(x=><div className="blocker" key={x}><ShieldAlert size={17}/><span>{x}</span></div>)}<div className="blocker success"><CheckCircle2 size={17}/><span>Context retained across conversations</span></div></section><section className="panel"><div className="panelHead"><div><span className="eyebrow">ACTIONS</span><h3>Run the next step</h3></div></div><button className="actionRow" onClick={()=>{toast('Documents opened');}}><FileCheck2/><div><b>Review documents</b><span>Inspect missing or verified items</span></div><ChevronRight/></button><button className="actionRow" onClick={async()=>{try{await api('/students/'+s.id+'/eligibility',{method:'POST'});await reload();toast('Eligibility review completed')}catch(e){toast(e.message)}}}><ClipboardCheck/><div><b>Run eligibility check</b><span>Preliminary automated review</span></div><ChevronRight/></button><button className="actionRow" onClick={()=>{toast('Counselor escalation prepared')}}><MessageCircle/><div><b>Escalate to counselor</b><span>Send context with the case</span></div><ChevronRight/></button></section></div></>}</div>}

function Documents({students,selected,setSelected,reload,toast}){const s=students.find(x=>x.id===selected)||students[0];const [file,setFile]=useState(null);const docs=s?Object.entries(s.documents):[];const verify=async doc=>{try{await api('/students/'+s.id+'/documents/'+encodeURIComponent(doc)+'/verify',{method:'POST'});await reload();toast(doc+' verified')}catch(e){toast(e.message)}};const upload=async()=>{if(!file||!s)return;const fd=new FormData();fd.append('file',file);try{await fetch(API+'/upload',{method:'POST',body:fd});toast('File uploaded to secure demo storage');setFile(null)}catch(e){toast('Upload failed')}};return <div className="page enter"><Top eyebrow="DOCUMENT INTELLIGENCE" title="Documents" text="A calm verification screen instead of a maze of tiny controls."/><div className="selectorBar"><select value={s?.id||''} onChange={e=>setSelected(e.target.value)}>{students.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="two"><section className="panel"><div className="panelHead"><div><span className="eyebrow">CHECKLIST</span><h3>{s?.name}'s documents</h3></div></div>{docs.map(([d,v])=><div className="docRow" key={d}><div className={'docIcon '+v}><FileText size={18}/></div><div><b>{d}</b><span>{v==='verified'?'Verified':'Needs review'}</span></div><span className={'docStatus '+v}>{v}</span>{v!=='verified'&&<button className="smallBtn" onClick={()=>verify(d)}>Verify</button>}</div>)}</section><section className="panel uploadBox"><Upload size={26}/><h3>Upload a document</h3><p>Choose a PDF or image for the demo storage workflow.</p><label className="filePick">{file?file.name:'Choose file'}<input type="file" accept=".pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary full" disabled={!file} onClick={upload}>Upload <Upload size={16}/></button></section></div></div>}

function Analytics({a,students}){const sources=Object.entries(a?.sources||{});return <div className="page enter"><Top eyebrow="INTELLIGENCE" title="Conversion analytics" text="Useful signals for the admissions team, without turning the screen into a spreadsheet from hell."/><div className="stats"><Stat icon={Users} label="Leads" value={a?.total??0} sub="Captured"/><Stat icon={Zap} label="Intent" value={a?.avg_score??0} sub="Average score"/><Stat icon={GraduationCap} label="Conversion" value={(a?.conversion??0)+'%'} sub="Lead → enrolled"/><Stat icon={FileCheck2} label="Pending docs" value={a?.pending_documents??0} sub="Need attention"/></div><div className="two"><section className="panel chart"><div className="panelHead"><div><span className="eyebrow">ACQUISITION</span><h3>Lead sources</h3></div></div>{sources.map(([k,v])=><Bar key={k} label={k} value={v} max={Math.max(1,a?.total||1)}/>)}</section><section className="panel chart"><div className="panelHead"><div><span className="eyebrow">STAGES</span><h3>Lifecycle distribution</h3></div></div>{Object.entries(students.reduce((x,s)=>(x[s.stage]=(x[s.stage]||0)+1,x),{})).map(([k,v])=><Bar key={k} label={label(k)} value={v} max={Math.max(1,students.length)}/>)}</section></div></div>}
function Bar({label,value,max}){return <div className="bar"><div><span>{label}</span><b>{value}</b></div><div className="barTrack"><i style={{width:`${Math.max(5,value/max*100)}%`}}/></div></div>}

function SettingsPage({dark,setDark,ai,toast}){
  const [testing,setTesting]=useState(false);
  const testGemini=async()=>{
    setTesting(true);
    try{const d=await api('/ai/test',{method:'POST'});toast('Gemini connection works: '+d.reply);}
    catch(e){toast(e.message)}
    finally{setTesting(false)}
  };
  return <div className="page enter"><Top eyebrow="CONTROL CENTER" title="Simple settings" text="One place for appearance and the AI connection."/><div className="settings"><section className="panel settingCard"><div className="setting"><div><b>Theme</b><span>Switch between the dark command interface and light mode.</span></div><button className="toggle" onClick={()=>setDark(v=>!v)}>{dark?<Moon size={16}/>:<Sun size={16}/>} {dark?'Dark':'Light'}</button></div><div className="setting"><div><b>Gemini AI</b><span>Google Gemini is called securely by FastAPI.</span></div><span className={ai?.configured?'connection on':'connection'}><i/> {ai?.configured?'KEY LOADED':'NOT CONFIGURED'}</span></div><div className="setting"><div><b>Model</b><span>Configured in backend/app/config.py</span></div><code>{ai?.model||'gemini-2.5-flash'}</code></div><div className="setting"><div><b>Connection test</b><span>This makes a real Gemini request and reports the actual error if it fails.</span></div><button className="smallBtn" disabled={testing||!ai?.configured} onClick={testGemini}>{testing?'Testing…':'Test Gemini'}</button></div></section><section className="panel setup"><div className="botIcon"><Bot size={20}/></div><span className="eyebrow">ONE-LINE API SETUP</span><h3>Connect Gemini</h3><p>Paste your key in exactly one place. You do not need to edit React or any other AI file.</p><pre>backend/app/config.py

GEMINI_API_KEY = "••••••••••••••••"</pre><div className="setupSteps"><span>1. Key stored in backend</span><span>2. Save file</span><span>3. Restart FastAPI</span><span>4. Test Gemini</span></div><button className="secondary" onClick={testGemini} disabled={testing||!ai?.configured}>{testing?'Testing…':'Test live connection'} <ArrowRight size={15}/></button></section></div></div>
}

createRoot(document.getElementById('root')).render(<App/>);
